# This is a basic workflow to help you get started with Actions

name: s3-sync-actions

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@main
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'

      run: 
      pip install awscli
      ls -al
      aws s3 sync . s3://yatah-bucket
